[package]
name = "pokers"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.17", features = ["derive"] }
rascii = "0.1.2"
rustemon = "3.5.0"
tokio = { version = "1.40.0", features = ["full"] }
